name: Deploy KChess (Lichess)

on:
  # Trigger khi có push lên nhánh main
  push:
    branches:
      - main
  # Trigger khi có pull request vào nhánh main
  pull_request:
    branches:
      - main
  # Tự động chạy mỗi 4 giờ
  schedule:
    - cron: '0 */4 * * *'  # Chạy mỗi 4 giờ
  # Trigger thủ công khi cần
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    # Kiểm tra mã nguồn từ GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Cài đặt Java (cho Scala)
    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    # Cài đặt SBT (Scala Build Tool)
    - name: Install SBT
      run: |
        curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.deb
        sudo dpkg -i sbt.deb
        sudo apt-get update
        sudo apt-get install sbt

    # Cài đặt Redis nếu cần (nếu bạn muốn chạy Redis)
    - name: Install Redis
      run: |
        sudo apt-get install redis-server

    # Build ứng dụng Scala (Lichess)
    - name: Build Lichess (KChess)
      run: sbt run

    # Triển khai lên Heroku (sử dụng heroku/heroku-deploy)
    - name: Deploy to Heroku
      uses: heroku/heroku-deploy@v3.0.3
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'kchess-app'  # Thay bằng tên app Heroku của bạn
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
